---
title: "Repository for Image Analysis Annotation"
format: html
---

# Repository for Image Analysis Annotation

This repository is designed for the management, organization, and utilization of images for annotation processes in image analysis projects. The following guidelines must be observed:

1. All images must be placed in the `library` folder.  
   - The script `code` contains the instructions for moving images in blocks.

2. It is necessary to ensure that images are not duplicated and are properly rotated before use.

3. The website associated with this repository will display only the content defined in the `index.qmd` file.  
   - The website must be built using the command:  
     ```bash
     quarto render website
     ```

4. The `library` folder will be hosted on the website, and each image will be assigned a unique URL.

5. Image URLs can be extracted using the code provided in `code.qmd`.

6. The generated links should be employed as references for annotations in *Label Studio*.


